cargo run --example dynamic_components
cargo run --example entity_basics
cargo run --example entity_hierarchy
cargo run --example entity_iterate_components
cargo run --example prefabs
cargo run --example relations
cargo run --example filters
cargo run --example hello_world
cargo run --example systems
